# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kyleskwon.github.io" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Kyle S. Kwon # Your name will go here
  description: "A personal portfolio and blog by Kyle S. Kwon" # used by search engines
  avatar: /img/portrait.JPG

  # Header and footer text
  header_text: >
     <h1>KYLE S. KWON</h1>
     <p>( Javascript-er ) &&  ( RubyonRails-er )</p>
#     <p>( Teacher ) && ( Photographer )</p>
  header_text_feature_image:
  footer_text: > 
        <h5>Kyle S. Kwon © 2016</h5
   

  # Icons
  rss: false
  email_address: kyleskwon@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble: 
  facebook: 
  flickr:
  github: kyleskwon # github profile name, e.g. "madebymunsters"
  google_plus:
  instagram: goldframes
  linkedin:  http://www.linkedin.com/in/kylekwon
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: amusingkyle
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-77766734-1"
  disqus_shortname: 'kyleskwon'
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Oswald:400normal, 'PT Sans Caption':400normal"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate]
